### PR TITLE
Update react and devpack, remove sharebar

### PR DESCRIPTION
**Pull request by sebinsua**
Update react and devpack, remove the old sharebar, and add the new image caption.

Once this is merged, it is somebody else's job to go back and update the styling (or even better, create a variant to add the styling.)

### CODE REVIEW

**Comment by keithamus** [comment]
Are we removing sharebar for good, or just for now?

**Comment by sebinsua** [comment]
I overheard that it wasn't going to be in the Gobbet?

Either way, these changes are mostly about getting this component up to react-0.14.0 and a version of the devpack that wasn't super old. The removal of the sharebar from this was incidental on the fact that it did not support 0.14.0 and Dan was still working on the second version.

**Comment by keithamus** [comment]
Need to mention it as a breaking change in the commit logs.

**Comment by sebinsua** [comment]
Alright.

**Comment by sebinsua** [comment]
Done. @keithamus

**Comment by keithamus** [comment]
Sorry - you also need to state that part of the breaking change is that the ShareBar is no longer featured.

**Comment by sebinsua** [comment]
Done.

**Comment by keithamus** [comment]
FYI in the future it might be better to enumerate each breaking feature as a list item.

**Pull request merged**
